backend:
  name: github
  repo: JoaoVinezof/joaovinezof.github.io
  branch: develop
  site_domain: joaovinezof.dev

  publish_mode: editorial_workflow
  media_folder: "static/assets/img"
  public_folder: "assets/img"

  collections:
    - name: "posts"
      label: "Posts"
      folder: "data/posts"
      create: true
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "select",
            options: ["blog-post"],
          }
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Description", name: "description", widget: "string" }
        - {
            label: "Category",
            name: "category",
            widget: "select",
            options: ["css", "php", "js", "html", "svg", "dev", "misc"],
          }
        - {
            label: "Date",
            name: "date",
            widget: "datetime",
            format: "YYYY-MM-DD hh:mm:ss",
          }
        - { label: "Tags", name: "tags", widget: "list" }
        - { label: "Body", name: "body", widget: "markdown" }
